### ISSUE TITLE
bootstrap4 for mvc5?

### ISSUE THREAD

**Issue by kbalint** [justdmitry/BootstrapMvc#10]
Hi, quick question: how can one install bootstrap4 for mvc5?
Install the Core package and the Bootstrap4 package separately? Thanks!

**Comment by justdmitry** [comment]
Not Core. Bootstrap4 and Mvc5.
See https://github.com/justdmitry/BootstrapMvc/tree/master/src/BootstrapMvc.Bootstrap4Mvc6 as a reference.

**Comment by kbalint** [comment]
Thanks, it is working. I've installed the BootstrapMvc.Bootstrap3MVC5 project originally, then removed the BootstrapMvc.Bootstrap3 package, and installed BootstrapMvc.Bootstrap4. This resulted in having BootstrapMvc.Mvc5 and BootstrapMvc.Core packages plus BootstrapMvc.Bootstrap4, and working.
